{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: fluentdlogger
  labels:
    app: fluentdlogger
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $port := .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.port }}
  {{- end }}
  selector:
    app: fluentdlogger
    release: {{ .Release.Name }}
{{- end }}
