version: "3.7"
services:
  cognitive-service:
    image: mcr.microsoft.com/azure-cognitive-services/language
    ports:
      - 5000:5000
    environment:
      - eula=accept
      - billing=<billing>
      - apikey=<apikey>
      - http_proxy=<proxy-address>
      - http_proxy_creds=<proxy-creds>