apiVersion: v1
kind: Service
metadata:
  name: language
spec:
  selector:
    app: language
  type: LoadBalancer
  ports:
    - name: language
      port: 5000
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: language
  labels:
    app: language
spec:
  replicas: 1
  selector:
    matchLabels:
      app: language
  template:
    metadata:
      labels:
        app: language
    spec:
      containers:
        - name: language
          image: mcr.microsoft.com/azure-cognitive-services/language
          env:
            - name: eula
              value: # accept
            - name: apikey
              value: # "<apikey>"
            - name: billing
              value: # "<billing>"
            - name: http_proxy
              value: # "<proxy-address>"
            - name: http_proxy_creds
              value: # "<proxy_creds>"
          ports:
            - containerPort: 5000
---