apiVersion: v1
kind: Service
metadata:
  name: face-frontend
  labels:
    run: face-frontend
spec:
  selector:
    app: face-frontend
  type: LoadBalancer
  ports:
  - name: front
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: face-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: face-frontend
    spec:
      containers:
      - name: face-frontend
        image: # Add frontend image name here
        ports:
        - name: public-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: public-port
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
      imagePullSecrets:
        - name: frontendregcred # add credentials for registry containing frontend app here
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: face
  labels:
    run: face
spec:
  selector:
    app: face
  type: LoadBalancer
  ports:
  - name: face
    port: 5000
    targetPort: 5000
    protocol: TCP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: face
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: face
    spec:
      containers:
      - name: face
        image: containerpreview.azurecr.io/microsoft/cognitive-services-face:latest
        ports:
        - name: public-port
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /status
            port: public-port
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
        args:
            - "eula=accept"
            - "apikey=apikeyplaceholder" # Add API Key here
            - "billing=billingpaceholder" # Add billing key here
      imagePullSecrets:
        - name: regcred # Add credentials for container preview registry here
      automountServiceAccountToken: false
