version: "3.7"
services:
  language-frontend:
    image: mcr.microsoft.com/azure-cognitive-services/samples/language/frontend
    ports:
      - "80:80"
  language:
    image: mcr.microsoft.com/azure-cognitive-services/language
    command: eula=accept billing=<FILL> apikey=<FILL>
    ports:
      - "5000:5000"
