apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: fluentdlogger
  labels:
    app: fluentdlogger
    version: {{ .Values.image.tag }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: fluentdlogger
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: fluentdlogger
        version: {{ .Values.image.tag }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: "{{ .Release.Service }}"
        kubernetes.io/cluster-service: "true"
        version: {{ .Values.image.tag }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: fluentdlogger
        image:  fluent/fluentd
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: libsystemddir
          mountPath: /host/lib
          readOnly: true
        - name: config-volume-fluentdlogger
          mountPath: /etc/fluent/config.d
        ports:          
{{- range $port := .Values.service.ports }}
          - name: {{ $port.name }}
            containerPort: {{ $port.port }}
{{- end }}
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      # It is needed to copy systemd library to decompress journals
      - name: libsystemddir
        hostPath:
          path: /usr/lib64
      - name: config-volume-fluentdlogger
        configMap:
          name: {{ template "fluentd.fullname" . }}
