apiVersion: v1
kind: PersistentVolume
metadata:
  name: luis-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  azureFile:
    secretNamespace: default
    secretName: brwals-aks-storage
    shareName: brwals-aks-share
    readOnly: true
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000