# Generic declaration of the kubernetes elements necessary for the cognitive service application

apiVersion: v1
kind: Service
metadata:
  name: language
  labels:
    run: language
spec:
  selector:
    app: language
  type: {{ .Values.Language.Service.type }}
  ports:
  - name: language
    port: 5000
    targetPort: 5000
    protocol: TCP
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: language
  labels:
    app: language
spec:
  replicas: {{ .Values.Language.Replicas }}
  selector:
    matchLabels:
      app: language
  template:
    metadata:
      labels:
        app: language
    spec:
      imagePullSecrets:
      - name: {{ .Values.Language.RegistrySecret }}
      containers:
      - name: language
        image: {{ .Values.Language.Image }}
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort:  5000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /status
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        args:
          - KeyVault:Vault=cscp-demo-keys
          - KeyVault:ClientId={{ .Values.Configuration.KeyVault.Id }}
          - KeyVault:ClientSecret={{ .Values.Configuration.KeyVault.Secret }}
          - eula=accept
          - Fluentd:Host=fluentdlogger
