Frontend:
  Replicas: 1
  Service:
    type: LoadBalancer
  Image: brwalsincubationregistry.azurecr.io/samples/languagefrontend:1030438
  RegistrySecret: brwalsregistry

Language:
  Replicas: 2
  Service:
    type: LoadBalancer
  Image: containerpreview.azurecr.io/microsoft/cognitive-services-language:1.1.006490002-amd64-preview
  RegistrySecret: containerpreviewregistry

Configuration:
  KeyVault:
    Id: 296432ba-7740-4c64-aa3d-8fff93f7e8c0
    Secret: DEFAULT_SECRET
