apiVersion: v1
kind: Service
metadata:
  name: luis-frontend
  labels:
    run: luis-frontend
spec:
  selector:
    app: luis-frontend
  type: LoadBalancer
  ports:
  - name: front
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: luis-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: luis-frontend
    spec:
      containers:
      - name: luis-frontend
        image: # < URI of the Frontend App image >
        ports:
        - name: public-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /status
            port: public-port
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
      imagePullSecrets:
        - name: # < Name of the registry secret providing access to the frontend image >
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: luis
  labels:
    run: luis
spec:
  selector:
    app: luis
  type: LoadBalancer
  ports:
  - name: face
    port: 5000
    targetPort: 5000
    protocol: TCP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: luis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: luis
    spec:
      containers:
      - name: luis
        image: # < URI of the LUIS Image >
        ports:
        - name: public-port
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /status
            port: public-port
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
        args:
            - "eula=accept"
            - "apikey=" # < API Key for the LUIS Service >
            - "billing=" # < LUIS billing endpoint URI >
        volumeMounts:
        - name: luis-storage
          mountPath: /input

      imagePullSecrets:
        - name: # < Name of the registry secret providing access to the LUIS image >

      automountServiceAccountToken: false

      volumes:
      - name: luis-storage
        azureFile:
          secretName: # < Name of the secret containing Azure Storage credentials >
          shareName: # < Name of the file share on Azure Storage containing the LUIS models >
          readOnly: true
