version: "3.7"
services:
  cognitive-service:
    image: mcr.microsoft.com/azure-cognitive-services/language
    ports:
      - 5000:5000
    environment:
      - eula=accept
      - billing=<billing>
      - apikey=<apikey>
  nginx:
    image: nginx
    ports:
      - 443:443
      - 8080:80
    volumes:
      - <path>/<to>/cert:/cert 
      - <path>/<to>/conf:/etc/nginx/conf.d/
