apiVersion: v1
kind: Namespace
metadata:
  name: language-https
  labels:
    name: language-https
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-cert
  namespace: language-https
type: Opaque
data:
  nginx.key: <base64 encoded key content>
  nginx.crt: <base64 encoded crt content>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: language-https
data:
  tls.conf: |
    server {
      listen              80;
      return 301 https://$host$request_uri;
    }

    server {
      listen              443 ssl;
      ssl_certificate     /cert/nginx.crt;
      ssl_certificate_key /cert/nginx.key;

      location / {
        proxy_pass http://localhost:5000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP  $remote_addr;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: language
  namespace: language-https
spec:
  selector:
    app: language
  type: LoadBalancer
  ports:
    - name: language-https
      port: 443
      targetPort: 443
    - name: language-http
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: language-https
  namespace: language-https
  labels:
    app: language
spec:
  replicas: 1
  selector:
    matchLabels:
      app: language
  template:
    metadata:
      labels:
        app: language
    spec:
      containers:
        - name: front-end
          image: nginx
          ports:
            - containerPort: 443
            - containerPort: 80
          volumeMounts:
            - name: nginx-cert
              readOnly: true
              mountPath: /cert
            - name: nginx-conf
              readOnly: true
              mountPath: /etc/nginx/conf.d/
        - name: language
          image: mcr.microsoft.com/azure-cognitive-services/language
          env:
            - name: eula
              value: accept
            - name: apikey
              value: "<apikey>"
            - name: billing
              value: "<billing>"
          ports:
            - containerPort: 5000
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: tls.conf
                path: tls.conf
        - name: nginx-cert
          secret:
            secretName: nginx-cert
---