Frontend:
  Replicas: 1
  Service:
    type: LoadBalancer
  Image: brwalsincubationregistry.azurecr.io/samples/languagefrontend:1030438

Language:
  Replicas: 1
  Service:
    type: LoadBalancer
  Image: cdpxlinuxtest.azurecr.io/artifact/3778aacf-5071-477d-bf36-594432c6133c/buddy/cognitive-services-language:1.1.006680001-alpha-1b7f6e73

Configuration:
  KeyVault:
    Id: 296432ba-7740-4c64-aa3d-8fff93f7e8c0
    Secret: DEFAULT_SECRET