version: "3.7"
services:
  cognitive-service:
    image: mcr.microsoft.com/azure-cognitive-services/language
    ports:
      - 5000:5000
    environment:
      - eula=accept
      - billing=<billing>
      - apikey=<apikey>
      - fluentd:host=fluentd
      - fluentd:port=24224
  fluentd:
    image: fluentd
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
